### ISSUE TITLE
Help developers build on top of Osmosis

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/docs#47]
This is an epic to capture the different components needed to help developers build with Osmosis. 

## Infrastructure
- [x] osmosis-labs/osmosis-infra#6

## Front end 
- [ ] Get started with Telescope

## Documentation
- [x] Expand the docs [here](https://docs.osmosis.zone/developing/#web-development)
