### ISSUE TITLE
[Epic] [Build] on Osmosis Docs

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/docs#78]
# Building dApps on Osmosis

- [x] Start Building
  - [ ] #81
  - [ ] In depth guide
- [x] Tools
  - [ ] Membrane
  - [ ] #82
  - [ ] #83
- [x] Join a network
  - [ ] Local Osmosis
  - [ ] Join the testnet
  - [ ] Join the main net
- [x] Osmosis daemon

# Building Osmosis Core

- [x] Getting Started
  - [x] Build and test
  - [ ] IDE Setup
- [x] Performance & Profiling
- [x] Join a network
  - [ ] Local Osmosis
  - [ ] Edge Testnet (Staging environment, stage branch)
     - [ ] Push latest version to stage before main
  - [x] Join the testnet
  - [x] Join the main net
- [x] Modules
  - [x] List of all modules

The following pages I’m not 100% sure where to put them under yet. 

- [ ] Key management
- [ ] Assets
- [ ] Relaying

Also, I think we need to create a new page for:

- [ ] #84
- [x] Guides
