### ISSUE TITLE
[Build] Quick guide

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/docs#81]
This guide is meant to get dApps developers up and running quickly. 

@xiangan 
As discussed earlier. I have put together an outline for the first quick guide on building dApps in Osmosis. As you become familiar with the tooling we will iterate and improve the guides.

Repo: **docs**
Branch: **stage**
Page to publish guide: https://stage-docs.osmosis.zone/developing/dapps/get_started/quick-guide.html

## Tasks

- [x] Membrane initial setup
- [ ] Use Membrane with the testnet
- [x] Create your first dApp 
   - [ ] Scaffold your dApp
   - [ ] Configure the testnet
   - [ ] Deploy
   - [x] Interact with the deployed contract
   - [ ] Front-end scaffolding
- [x] Use Membrane with LocalOsmosis
   - [x] Install and run LocalOsmosis
   - [ ] Scaffold your dApp
   - [x] Configure the testnet
   - [ ] Deploy
   - [x] Interact with the deployed contract
   - [ ] Front-end scaffolding

Please add more to this guide as we become familiar with the tooling.

**Comment by daniel-farina** [comment]
Closing this as we have a good guide for CLI. The frontend bootstraping will be done with Beaker.
